Repository AY2425S2-CS2103-F15-4/tp, pull requests merged in 2025-04, with the labels that each got.

#204 Update UG for edit, tag and export commands
  docs/UserGuide.md
Labels: priority.High

#202 Support all contacts update max score and minor bug fixes for Lab
  src/main/java/seedu/tassist/logic/commands/UpdateLabScoreCommand.java
  src/main/java/seedu/tassist/logic/parser/UpdateLabScoreCommandParser.java
  src/main/java/seedu/tassist/model/Operations.java
  src/main/java/seedu/tassist/model/person/LabScore.java
  src/main/java/seedu/tassist/model/person/LabScoreList.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/tassist/logic/commands/UpdateLabScoreCommandTest.java
  src/test/java/seedu/tassist/model/person/LabScoreTest.java
  src/test/java/seedu/tassist/testutil/TypicalPersons.java
Labels: type.Task

#206 Fix delete command bugs
  src/main/java/seedu/tassist/logic/Messages.java
  src/main/java/seedu/tassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/tassist/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/tassist/logic/parser/ParserUtil.java
  src/test/java/seedu/tassist/logic/LogicManagerTest.java
  src/test/java/seedu/tassist/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/tassist/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/tassist/logic/parser/ParserUtilTest.java
  src/test/java/seedu/tassist/logic/parser/UpdateLabScoreCommandParserTest.java
Labels: alpha-bug

#232 Update undo redo command
  src/main/java/seedu/tassist/logic/commands/RedoCommand.java
  src/main/java/seedu/tassist/logic/commands/UndoCommand.java
  src/main/java/seedu/tassist/logic/parser/AddressBookParser.java
  src/main/java/seedu/tassist/model/Operations.java
  src/main/java/seedu/tassist/model/Snapshot.java
  src/main/java/seedu/tassist/model/person/LabScoreList.java
  src/test/java/seedu/tassist/model/SnapshotTest.java
Labels: priority.High

#218 Resolve search issue #199
  src/main/java/seedu/tassist/logic/commands/SearchCommand.java
  src/main/java/seedu/tassist/logic/parser/SearchCommandParser.java
  src/main/java/seedu/tassist/model/person/PersonMatchesPredicate.java
  src/test/java/seedu/tassist/logic/parser/SearchCommandParserTest.java
Labels: alpha-bug

#213 Update GUI and relevant UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/Ui.png
  docs/images/UiExtend.png
  src/main/java/seedu/tassist/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: alpha-bug

#216 Create toggle command for UI view
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiExtend.png
  docs/images/UiToggle.png
  src/main/java/seedu/tassist/logic/commands/CommandResult.java
  src/main/java/seedu/tassist/logic/commands/ExitCommand.java
  src/main/java/seedu/tassist/logic/commands/HelpCommand.java
  src/main/java/seedu/tassist/logic/commands/ToggleCommand.java
  src/main/java/seedu/tassist/logic/parser/AddressBookParser.java
  src/main/java/seedu/tassist/ui/MainWindow.java
  src/main/java/seedu/tassist/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/tassist/logic/commands/CommandResultTest.java
  src/test/java/seedu/tassist/logic/commands/ExitCommandTest.java
  src/test/java/seedu/tassist/logic/commands/HelpCommandTest.java
  src/test/java/seedu/tassist/logic/commands/ToggleCommandTest.java
Labels: priority.High

#219 Bug Fix: Handle missing and extra CSV fields in CsvUtil
  src/main/java/seedu/tassist/commons/util/CsvUtil.java
  src/main/java/seedu/tassist/logic/commands/LoadDataCommand.java
Labels: alpha-bug

#234 Bug fix
  docs/DeveloperGuide.md
  src/main/java/seedu/tassist/logic/commands/UpdateLabScoreCommand.java
  src/main/java/seedu/tassist/logic/parser/AddressBookParser.java
  src/main/java/seedu/tassist/model/Operations.java
  src/main/java/seedu/tassist/model/Snapshot.java
  src/main/java/seedu/tassist/model/person/LabScore.java
  src/main/java/seedu/tassist/model/person/LabScoreList.java
  src/test/java/seedu/tassist/model/SnapshotTest.java
Labels: alpha-bug
