Repository AY2425S2-CS2103-F15-4/tp, pull requests merged in 2025-03, with the labels that each got.

#93 Update delete command flag
  docs/UserGuide.md
  src/main/java/seedu/tassist/commons/core/index/Index.java
  src/main/java/seedu/tassist/logic/Messages.java
  src/main/java/seedu/tassist/logic/commands/DeleteCommand.java
  src/main/java/seedu/tassist/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/tassist/logic/LogicManagerTest.java
  src/test/java/seedu/tassist/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/tassist/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/tassist/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#127 Update error message format for add command and UI dropdown option
  src/main/java/seedu/tassist/logic/Messages.java
  src/main/java/seedu/tassist/logic/commands/AddCommand.java
  src/main/java/seedu/tassist/logic/parser/AddCommandParser.java
  src/main/java/seedu/tassist/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/tassist/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/tassist/model/person/Email.java
  src/main/java/seedu/tassist/ui/PersonCard.java
  src/main/java/seedu/tassist/ui/PersonListPanel.java
  src/test/java/seedu/tassist/logic/parser/AddCommandParserTest.java
Labels: severity.High

#138 Update matriculation number information
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/tassist/model/person/MatNum.java
Labels: severity.High

#148 Fix Mark Attendance bug while loading the json
  src/main/java/seedu/tassist/model/person/AttendanceList.java
  src/main/java/seedu/tassist/ui/PersonCard.java
  src/test/java/seedu/tassist/model/person/AttendanceListTest.java
Labels: type.Bug, severity.High

#151 Add support for bulk marking of attendance
  src/main/java/seedu/tassist/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/tassist/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/tassist/logic/parser/ParserUtil.java
  src/main/java/seedu/tassist/model/person/TutGroup.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/tassist/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/tassist/logic/parser/MarkAttendanceCommandParserTest.java
  src/test/java/seedu/tassist/logic/parser/ParserUtilTest.java
  src/test/java/seedu/tassist/model/person/TutGroupTest.java
Labels: priority.Medium
